%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\SEM 6\MathModeling\Workplace\npmcm_2018f\InputData.xlsx
%    Worksheet: Pucks
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/09/15 21:15:37

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('D:\SEM 6\MathModeling\Workplace\npmcm_2018f\InputData.xlsx','Pucks','A2:L754','',@convertSpreadsheetExcelDates);
arriveTime=[];
depTime=[]
for i=1:size(raw, 1)
    raw{i,3} = raw{i,3}*24;
    raw{i,8} = raw{i,8}*24;
    arriveTime = [arriveTime raw{i,3}];
    depTime = [depTime raw{i,8}];
    tmp =raw{i,6};
    if isnumeric(tmp)
        raw(i,6) = {num2str(tmp)};
    end
end

% stringVectors = string(raw(:,[1,2,4,5,6,7,9,10,11,12]));
pucks.pucksNum = string(raw(:,1));
pucks.arriveDate = string(raw(:,2));
pucks.arriveTime = arriveTime;
pucks.arriveFlightNum = string(raw(:,4));
pucks.arriveType = string(raw(:,5));
pucks.flightCat = string(raw(:,6));
pucks.depDate = string(raw(:,7));
pucks.depTime = depTime;
pucks.depFlightNum = string(raw(:,9));
pucks.depType = string(raw(:,10));
pucks.upAirport = string(raw(:,11));
pucks.downAirport = string(raw(:,12));
save pucks pucks

%% 
clear all;clc
[~, ~, raw, dates] = xlsread('D:\SEM 6\MathModeling\Workplace\npmcm_2018f\InputData.xlsx','Tickets','A2:F4797','',@convertSpreadsheetExcelDates);
passNum=[];
for i=1:size(raw,1)
    passNum=  [passNum raw{i,2}];
end
tickets.passTicket = string(raw(:,1));
tickets.passNum = passNum;
tickets.arriveFlightNum = string(raw(:,3));
tickets.arriveDate = string(raw(:,4));
tickets.depFlightNum = string(raw(:,5));
tickets.depDate = string(raw(:,6));
save tickets tickets

%%
clear all;clc
[~, ~, raw, dates] = xlsread('D:\SEM 6\MathModeling\Workplace\npmcm_2018f\InputData.xlsx','Gates','A2:F70','',@convertSpreadsheetExcelDates);

for i=1:size(raw,1)
    if all(raw{i,4}=='D, I')
        raw{i,4}='B';
    end
    if all(raw{i,5}=='D, I')
        raw{i,5}='B';
    end
end
gates.gateName = string(raw(:,1));
gates.terminal = string(raw(:,2));
gates.area= string(raw(:,3));
gates.arriveType = string(raw(:,4));
gates.depType = string(raw(:,5));
gates.flightType = string(raw(:,6));
save gates gates
